services:
  database:
    image: postgres:${POSTGRES_VERSION:-18}-alpine
    environment:
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-greenlightP@$$w0rd}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-greenlight}", "-U", "${POSTGRES_USER:-greenlight}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - greenlight_box_data:/var/lib/postgresql/18/docker:rw

  migrate:
    image: migrate/migrate:${MIGRATE_VERSION:-v4.19.1}
    volumes:
      - ./migrations:/migrations
    depends_on:
      database:
        condition: service_healthy
    profiles: ["tools"]

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025" # Web UI port
      - "1025:1025" # SMTP port

volumes:
  greenlight_box_data: